name: sage_flutter
description: A new Flutter project with Serverpod.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  sage_client:
    path: ../sage_client

  serverpod_flutter: 2.1.5
  serverpod_auth_client: 2.1.5
  serverpod_auth_email_flutter: 2.1.5
  serverpod_auth_shared_flutter: 2.1.5

  auto_route: ^9.2.2
  collection: ^1.18.0
  flutter_form_builder: ^9.5.0
  flutter_hooks: ^0.20.5
  form_builder_validators: ^11.0.0
  hooks_riverpod: ^2.6.1
  infinite_scroll_pagination: ^4.0.0
  riverpod_annotation: ^2.6.1
  animations: ^2.0.11
  google_fonts: ^6.2.1
  sliver_tools: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_lints: '>=3.0.0 <6.0.0'
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/ginger-cat/
