name: sage
description: A new Flutter project.
version: 0.1.0+000100
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.1
  artemis: ^7.1.1-beta.1
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  gql: ^0.13.0
  gql_dedupe_link: ^2.0.0
  gql_exec: ^0.3.0
  gql_http_link: ^0.4.0
  gql_link: ^0.4.0
  local_auth: ^1.1.8
  package_info: ^2.0.2
  path_provider: ^2.0.5
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.2.4
  grinder: ^0.9.0

flutter:
  uses-material-design: true
