name: sage
description: A new Flutter project.
version: 0.1.0+000100
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.1
  artemis: ^7.1.1-beta.1
  firebase_auth: ^3.1.2
  firebase_core: ^1.7.0
  flutter_hooks: ^0.17.0
  flutter_signin_button: ^2.0.0
  google_fonts: ^2.1.0
  gql: ^0.13.0
  gql_dedupe_link: ^2.0.0
  gql_exec: ^0.3.0
  gql_http_link: ^0.4.0
  gql_link: ^0.4.0
  hooks_riverpod: ^0.14.0+4
  local_auth: ^1.1.8
  package_info: ^2.0.2
  path_provider: ^2.0.5
  riverpod: ^0.14.0+3
  shared_preferences: ^2.0.8
  sign_in_with_apple: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.2.4
  grinder: ^0.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ginger-cat/
    - assets/images/login/
