defmodule Sage.Repo.Migrations.AddQuestionColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :admin, :boolean, default: false
    end

    alter table(:questions) do
      add :description, :text, null: false, default: ""
      add :required, :boolean, null: false, default: false
      add :attributes, :map, null: false
    end
  end

  def down do
    alter table(:questions) do
      remove :attributes
      remove :required
      remove :description
    end

    alter table(:users) do
      modify :admin, :boolean, default: nil
    end
  end
end