defmodule Sage.Repo.Migrations.AddUserAndTokens do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :archived_at, :utc_datetime_usec
      add :id, :uuid, null: false, primary_key: true
      add :email, :text, null: false
      add :name, :text, null: false
      add :hashed_password, :text, null: false
      add :admin, :boolean, null: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:users, [:email],
             where: "archived_at IS NULL",
             name: "users_unique_email_index"
           )

    create table(:user_tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    alter table(:surveys) do
      add :owner_id,
          references(:users,
            column: :id,
            name: "surveys_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:surveys, "surveys_owner_id_fkey")

    alter table(:surveys) do
      remove :owner_id
    end

    drop table(:user_tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end